name: Maven CI

on: [push]

jobs:
  build-universal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create staging directory
        run: mkdir -p staging
      - run: cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Universal Package
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: unstable-universal
          files: |
            staging/*.jar
            !staging/original*
